### PR TITLE
MacOS VNC specifics for os_instructions_source.md

### PR DESCRIPTION
**Pull request by jmhogan**
Able to make Mac instructions basically identical to Windows instructions, with specifics on how to access the built-in VNC viewer.

### CODE REVIEW

**Comment by caredg** [comment]
Hi @jmhogan, I missed this PR.  Is this still something that needs to be changed/added.  Maybe some direct changes got in conflict with this PR, could you please check this? I can then go ahead and merge if needed. Thanks!

**Comment by jmhogan** [comment]
I think its not important given that someone already put the html or
whatever in the main lesson page!

**Comment by caredg** [comment]
Right, but this page needs to be in sync.  If there is any change, here's where it should be.  Copying the html can be done at any time and it will most certainly be done before releasing the pre-exercises to make sure everything is up-to-date.

**Comment by caredg** [comment]
seems to be already there

**Pull request closed without merging**
